import { s } from './styledProxy';

// Export common styled components for backwards compatibility and better IDE support
export const Main = s.main;
export const Section = s.section;
export const Header = s.header;
export const Footer = s.footer;
export const Article = s.article;
export const Div = s.div;
export const Button = s.button;
export const Input = s.input;
export const Textarea = s.textarea;
export const Select = s.select;
export const Fieldset = s.fieldset;
export const Form = s.form;
export const Label = s.label;
export const P = s.p;
export const H1 = s.h1;
export const H2 = s.h2;
export const H3 = s.h3;
export const H4 = s.h4;
export const H5 = s.h5;
export const H6 = s.h6;
export const Ul = s.ul;
export const Ol = s.ol;
export const Li = s.li;
export const Code = s.code;
export const Pre = s.pre;
export const Time = s.time;
export const Span = s.span; 